Date helper datetime support
maennchen/crontab pull request #129
Opened 2024-02-12 15:36 UTC by shaolang

@maennchen I've simplified `date_helper` with an extracted `add/3` function. As focus switches to testing that new function rigorously, I have to make it public during tests, I used PragDave's [private](https://hexdocs.pm/private/Private.html) library to keep `add/3` private in non-test environments,

Functions in `date_helper` are now all able to do datetime arithmetic correctly, even for time gaps when daylight savings starts, and ambiguous times when daylight savings ends.

One thing to note is that for ambiguous times when daylight saving ends, I've chosen to return the time with the standard timezone, e.g., between Eastern Daylight Time (EDT) and Eastern Standard Time (EST), `add/3` returns the time with EST. If you think it should return EDT instead, let me know, and I'll change it to that.

2024-02-12 15:51 UTC, maennchen commented
Thanks a lot for the PR!

This is just the feedback for a quick glance over the code. I'll do a more thorough review later.

* I would like to avoid adding an extra dependency for private functions. Specifying @moduledoc / @doc false should ve sufficient.
* Since the DateHelper module is not part of the public API, we should also not define types there. (Doc link will not work)
* I think triggering twice for ambigous datetimes would be technically correct. But it could make sense making the behavior configurable.

A cron expression, which runs every 5 minutes should also do so when DST changes.

A cron expression running at 2:30 AM every day however should not.

I'm thinking if it would therefore make sense to introduce an option argument where you could choose both, first or last. (Naming tbd)

2024-02-12 16:22 UTC, shaolang commented
I've removed private as a dependency and reinstated the date type in `DateChecker`.

Hmmm... ambiguous times are really a headache. I chose to return one of the instances is due to [AWS EventBridge Scheduler's behavior](https://docs.aws.amazon.com/scheduler/latest/UserGuide/schedule-types.html#daylist-savings-time). AWS' scheduer skips running when there's a gap, and runs only once when there's ambiguity.

Nevertheless, you let me know how you'll like to proceed from here. We are getting closer to closing #69 and improving all crontab dependents :)

2024-02-12 18:24 UTC, maennchen reviewed
> Hmmm... ambiguous times are really a headache. I chose to return one of the instances is due to AWS EventBridge Scheduler's behavior. AWS' scheduer skips running when there's a gap, and runs only once when there's ambiguity.

I think we should let the user decide.

What do you think about adding `on_ambiguous_time_trigger` to the `CronExpression` struct? The values would be `both`, `earlier`, `later` and default to `later`.

Like this the user can decide how he wants to handle this edge-case.

We would then pass it through as an option in a keyword list to the `DateHelper`.

2024-02-12 18:24 UTC, maennchen commented on lib/crontab/date_helper.ex
> +  def dec_year(date), do: add(date, -days_in_year(date), :day)
We might have a bug here. (Also in the implementation before.)

Given date `2024-02-01` (before leap day), I think we subtract one day too much.

Same with increment if we're after the leap day.

2024-02-12 18:24 UTC, maennchen commented on lib/crontab/date_helper.ex
> +      Date.new!(year, month, day)
```suggestion
      date
```

2024-02-12 18:44 UTC, maennchen commented on lib/crontab/date_helper.ex
> +    case adjusted.std_offset == candidate.std_offset do
use an if for booleans

2024-02-12 18:50 UTC, maennchen commented on test/crontab/date_helper_test.exs
> +      Calendar.put_time_zone_database(Tz.TimeZoneDatabase)
We could also put this into a config/config.exs file since that is not read for libraries.

2024-02-13 00:14 UTC, shaolang commented on lib/crontab/date_helper.ex
>      weekday = :calendar.day_of_the_week(year, month, day)
That was in the original code. I'll change it to `Date.day_of_week/1`.

2024-02-13 04:56 UTC, shaolang commented
> > Hmmm... ambiguous times are really a headache. I chose to return one of the instances is due to AWS EventBridge Scheduler's behavior. AWS' scheduer skips running when there's a gap, and runs only once when there's ambiguity.
> 
> I think we should let the user decide.
> 
> What do you think about adding `on_ambiguous_time_trigger` to the `CronExpression` struct? The values would be `both`, `earlier`, `later` and default to `later`.
> 
> Like this the user can decide how he wants to handle this edge-case.
> 
> We would then pass it through as an option in a keyword list to the `DateHelper`.

Sounds good to me.

Question then is: does that mean most functions in `DateHelper` need to return either one or two dates?

2024-02-13 05:36 UTC, maennchen commented
> does that mean most functions in DateHelper need to return either one or two dates?

Probably not:

If you have the setting on both, we can just return the first occurrence. When we look for the next candidate date, we should automatically reach the later occurrence.

So the logic could be something like this:

* if result ambiguous and setting is `earlier`: return earlier
* if result ambiguous and setting is `later`: return later
* if result ambiguous and setting is `both`: return earlier or later depending on `adjusted`

2024-02-13 06:21 UTC, shaolang commented
I've addressed the issues in the review. I've also added targeted tests for `inc_year/1` and `dec_year/1` to ensure the edge cases are covered.

2024-02-13 06:40 UTC, maennchen commented
@shaolang Do I understand correct that you want to send a secod PR for the ambiguity habdling?

2024-02-13 06:41 UTC, shaolang commented
> @shaolang Do I understand correct that you want to send a secod PR for the ambiguity habdling?

Yes. Are you closing this PR prior to that? I'm okay with keep this or submitting a new PR.

2024-02-13 06:43 UTC, maennchen requested changes

2024-02-13 06:43 UTC, maennchen commented on lib/crontab/date_helper.ex
> +  # defp day_in_last_month(%{year: year, month: month}),
Can we remove commeted out code?

2024-02-13 06:43 UTC, maennchen commented on lib/crontab/date_helper.ex
> +      Date.new!(year, month, day)
```suggestion
      date
```

2024-02-13 06:44 UTC, shaolang commented on lib/crontab/date_helper.ex
> +  # defp day_in_last_month(%{year: year, month: month}),
sorry, my bad.

2024-02-13 06:47 UTC, maennchen commented
Separate work for me. But I‘ll merge directly onto `main`. We‘ll just do PR 2 before I cut a release.

Amazing work, thanks a lot for your efforts!

2024-02-13 07:03 UTC, maennchen approved these changes

2024-02-13 07:03 UTC, merged

2024-10-22 19:07 UTC, maennchen commented
@shaolang Are you still planning to open a PR for the ambiguous date handling?

I don't really have the time to address it myself and I won't be able to release your work if it is incomplete.

2024-10-23 00:32 UTC, shaolang commented
Yes, I do. I have been pretty busy with work since the contribution. I foresee some down time towards the end of the year, so I'll pick it up again and hopefully complete it before the year ends.